name: main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Go Format
        run: gofmt -s -w -l $(find . -type f -name '*.go'| grep -v "/vendor/") && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        env:
          DOCKER_IMAGE: ghcr.io/alsosee/r2action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          platforms: linux/amd64
